name: Build & Deploy (Vite → gh-pages)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ⬇️ usa npm install (no 'npm ci', que falla si no hay package-lock)
      - run: npm install

      - run: npm run build

      # 404 para SPA en GitHub Pages
      - run: cp dist/index.html dist/404.html

      # Publica en la rama gh-pages (la crea si no existe)
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
